"""Initial database schema

Revision ID: 1dd0c571c561
Revises: 
Create Date: 2026-01-09 18:34:28.830369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd0c571c561'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_result_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('cve', sa.String(length=50), nullable=True),
    sa.Column('cvss_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_result_id'), 'findings', ['scan_result_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_scan_id'), 'scan_results', ['scan_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modules', sa.JSON(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_scan_results_scan_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_findings_scan_result_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
