"""Markdown reporter for my-check scan results."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from my_check.types import CheckCategory, CheckResult, CheckStatus, Report
from rich.console import Console

_STATUS_EMOJI: dict[CheckStatus, str] = {
    CheckStatus.PASS: "✅",
    CheckStatus.WARN: "⚠️",
    CheckStatus.FAIL: "❌",
    CheckStatus.INFO: "ℹ️",
}

_SCORE_BADGE = {
    "high": "🟢",
    "mid": "🟡",
    "low": "🔴",
}


def _score_badge(score: float) -> str:
    if score > 80:
        return _SCORE_BADGE["high"]
    if score > 50:
        return _SCORE_BADGE["mid"]
    return _SCORE_BADGE["low"]


def _normalize_issues(details: Any) -> list[dict[str, str]]:
    if isinstance(details, list):
        return [d for d in details if isinstance(d, dict)]
    if isinstance(details, dict) and "issues" in details:
        return [d for d in details["issues"] if isinstance(d, dict)]
    return []


def _md_table(rows: list[dict[str, str]], limit: int = 20) -> str:
    if not rows:
        return ""
    all_keys: list[str] = []
    seen: set[str] = set()
    for row in rows[:limit]:
        for k in row:
            if k not in seen:
                all_keys.append(k)
                seen.add(k)

    header = "| " + " | ".join(all_keys) + " |"
    sep = "| " + " | ".join("---" for _ in all_keys) + " |"
    lines = [header, sep]
    for row in rows[:limit]:
        cells = [str(row.get(k, "")).replace("|", "\\|").replace("\n", " ") for k in all_keys]
        lines.append("| " + " | ".join(cells) + " |")
    if len(rows) > limit:
        lines.append(f"\n_… and {len(rows) - limit} more issue(s)._")
    return "\n".join(lines)


@dataclass(slots=True)
class MarkdownReporter:
    """Write scan results as a Markdown report file."""

    output_dir: Path

    def emit(self, report: Report) -> None:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        console = Console(stderr=True)

        md = self._build(report)
        path = self.output_dir / "my-check-report.md"
        path.write_text(md, encoding="utf-8")
        console.print(f"[green]✓[/green] Markdown report → [cyan]{path}[/cyan]")

    # ------------------------------------------------------------------

    def _build(self, report: Report) -> str:
        now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        score = report.global_score
        badge = _score_badge(score)
        s = report.summary

        lines: list[str] = [
            "# 🔒 my-check Security Report",
            "",
            f"**Target:** `{report.target}`  ",
            f"**Date:** {now}  ",
            f"**Global Score:** {badge} `{score:.1f}/100`  ",
            "",
            "## Summary",
            "",
            "| Status | Count |",
            "| --- | --- |",
            f"| ✅ Pass  | {s[CheckStatus.PASS]} |",
            f"| ⚠️ Warn  | {s[CheckStatus.WARN]} |",
            f"| ❌ Fail  | {s[CheckStatus.FAIL]} |",
            f"| ℹ️ Info  | {s[CheckStatus.INFO]} |",
            "",
        ]

        by_cat = report.by_category
        for cat in CheckCategory:
            items = by_cat.get(cat)
            if not items:
                continue

            cat_label = "🌐 Web Checks" if cat == CheckCategory.WEB else "☸️ Kubernetes Checks"
            lines += [f"## {cat_label}", ""]

            # Overview table
            lines += [
                "| Check | Status | Score | Message |",
                "| --- | :---: | ---: | --- |",
            ]
            for check_id, result in items:
                emoji = _STATUS_EMOJI[result.status]
                score_cell = f"{_score_badge(result.score)} {result.score}"
                lines.append(
                    f"| `{check_id}` | {emoji} {result.status.value} "
                    f"| {score_cell} | {result.message} |"
                )
            lines.append("")

            # Detail sections for failed/warn
            for check_id, result in items:
                if result.status not in (CheckStatus.FAIL, CheckStatus.WARN):
                    continue
                lines += self._detail_section(check_id, result)

        if report.errors:
            lines += ["## ⛔ Errors", ""]
            for check_id, err in report.errors.items():
                lines.append(f"- **{check_id}**: {err}")
            lines.append("")

        lines += [
            "---",
            "_Generated by [my-check](https://github.com/KevinDeBenedetti/web-check)_",
        ]
        return "\n".join(lines)

    def _detail_section(self, check_id: str, result: CheckResult) -> list[str]:
        emoji = _STATUS_EMOJI[result.status]
        lines: list[str] = [
            f"### {emoji} `{check_id}` — Details",
            "",
        ]

        issues = _normalize_issues(result.details)
        if issues:
            lines.append(_md_table(issues))
            lines.append("")

        if result.remediation:
            lines += [
                f"> 💡 **Remediation:** {result.remediation}",
                "",
            ]
        return lines
